### ISSUE TITLE
No module names mechanize

### ISSUE THREAD

**Issue by ViroDaHaxr** [UltimateHackers/Striker#17] opened 2017-11-22 08:19 UTC
raceback (most recent call last):
  File "striker.py", line 2, in <module>
    import mechanize
ImportError: No module named mechanize

**Comment by UltimateHackers** [comment] 2017-11-22 14:44
You have to install this python library manually.
Its not a bug of Striker hence I am closing this issue.
Regards!

**Closed by UltimateHackers** 2017-11-22 14:44 UTC
